# Datasets 

## Gridded Data
### gridMET (meterology)

One of the primary forms of drought is meteorological drought. Therefore, having a strong understanding of meteorological events and anomalies is a critical consideration in drought monitoring. The core meteorological data set used in the UMRB Drought Dashboard is gridMet. gridMET is a gridded (spatial) dataset that provides estimates of meteorological conditions such as precipitation, temperature, wind speed, reference evapotranspiration, etc. As described by the authors of gridMET:

"gridMET blends spatial attributes of gridded climate data from PRISM with desirable temporal attributes (and additional variables) from regional reanalysis (NLDAS-2) using climatically aided interpolation. The resulting product is a spatially and temporally complete, high-resolution (1/24th degree ~4-km) gridded data set of surface meteorological variables."

gridMET was chosen as the primary meteorological data set for the UMRB Drought Dashboard for a few key reasons. Firstly, it reliably provides data at a daily time step with low latency (~2 days, e.g. the lag before data is available to process). This means that data is available quickly for use in drought assessment, aiding in the rapid evaluation of quickly changing conditions.  Secondly, it provides data at an appropriate spatial resolution (~4km) for operational drought monitoring. Because drought monitoring is conducted at regional spatial scales, 4km data provides more that proficient spatial detail and wall-to-wall coverage across the domain. Finally, and perhaps most importantly, gridMET provides the lowest bias and mean absolute error when compared to alternative gridded data sets of similar nature to the [MT Mesonet](https://climate.umt.edu/mesonet/), an independent observational data set. This analysis is currently being formalized and will be appended to this document upon completion. 

More information on gridMET can be found [here](https://www.climatologylab.org/gridmet.html).

Citation: Abatzoglou, J. T. (2013), [Development of gridded surface meteorological data for ecological applications and modelling](http://onlinelibrary.wiley.com/doi/10.1002/joc.3413/full).  Int. J. Climatol., 33: 121–131.

---

### SNODAS (snowpack)

Estimates of snow pack accumulation and melt are critical information to assess winter time water storage scross the UMRB. One dataset used within the UMRB Drought Dashboard to describe snow water equivalent (SWE) is provided by the NOAA National Weather Service's National Operational Hydrologic Remote Sensing Center (NOHRSC) SNOw Data Assimilation System (SNODAS). SNODAS is a modeling and data assimilation system developed by NOHRSC to provide the best possible estimates of snow cover and associated parameters to support hydrologic modeling and analysis. 

More information on SNODAS can be found [here](https://nsidc.org/data/g02158).

Citation: National Operational Hydrologic Remote Sensing Center. 2004. Snow Data Assimilation System (SNODAS) Data Products at NSIDC, Version 1. [Indicate subset used]. Boulder, Colorado USA. NSIDC: National Snow and Ice Data Center. doi: [https://doi.org/10.7265/N5TB14TC](https://doi.org/10.7265/N5TB14TC). [Date Accessed].

---

### SMAP (soil moisture)

The Soil Moisture Active Passive (SMAP) mission (run by NASA) is a satellite that measures the amount of water in the surface soil everywhere on Earth. SMAP is designed to measure soil moisture every 2-3 days providing a critical source of information to assess regional soil moisture conditions. The UMRB drought dashboard uses SMAP Level 3 soil moisture observations which have been integrated into a modified two-layer Palmer model using a 1-D Ensemble Kalman Filter (EnKF) data assimilation approach. This allows for the evaluation of surface and subsurface soil moisture conditions across the UMRB. 

More information on SMAP can be found [here (NASA official page)](https://smap.jpl.nasa.gov) and [here (data access page)](https://developers.google.com/earth-engine/datasets/catalog/NASA_USDA_HSL_SMAP10KM_soil_moisture).

---

### GRACE (groundwater)

Groundwater anomalies are a key drought indicator, especially when considering long timescales and deep moisture reservoirs often utilized in agriculture. However, groundwater is notoriously difficult to measure and when observed (using wells for example), often only represents conditions at a local point. To aid in measuring groundwater dynamics across the globe, NASA's Gravity Recovery and Climate Experiment (GRACE) program was launched to accurately map variations in Earth's gravity field. These observations of gravity provide observations of variations of mass associated with runoff and ground water storage on land masses. Here, we use a GRACE informed indicator of groundwater availability based on terrestrial water storage observations derived from GRACE-FO satellite data which is then integrated with other observations, using a land surface water and energy model. 

More information on GRACE can be found [here](https://www.nasa.gov/mission_pages/Grace/index.html) and more information on the GRACE based groundwater drought indicator can be found [here](https://nasagrace.unl.edu/).

---

### MODIS (vegitation)

MODIS (or Moderate Resolution Imaging Spectroradiometer) is a key instrument aboard the Terra and Aqua satellites run by NASA. The MODIS sensors are sensitive to biologically relevant light reflections that allow for the estimation of vegetation growth, health and drought response. One of the key data sets derived from the MODIS sensors is the Normalized Difference Vegetation Index (NDVI). NDVI is a commonly used indicator of ecosystem photosynthesis and provides an indication of vegetation status. Alternative vegetation indicies (such as the Enhanced Vegetation Index - EVI) are also available from MODIS. MODIS data is used in the UMRB drought dashboard to provide regional information on vegetation drought response and ecosystem drought conditions. 

More information on the MODIS sensors can be found [here](https://modis.gsfc.nasa.gov/) and more information on the specific dataset used within the UMRB drought dashboard can be found [here](https://developers.google.com/earth-engine/datasets/catalog/MODIS_MOD09GA_006_NDVI).

---

## Point Data

### MT Mesonet (meteorology and soil moisture)

The Montana Climate Office (MCO) is leading the development of a cooperative statewide soil moisture and meteorological information system. It is designed to support decision-making in agriculture, range and forested watershed contexts. This network will add new remote sites and integrate existing cooperator networks to develop the first statewide soil-climate network. No one entity can ensure sustained operation and success of a statewide climate and soil moisture information network. The MCO is embracing a cooperative context that will address a diverse set of information needs. 

---

### SNOTEL (snowpack)

SNOTEL is an automated system of snow pack and related environmental sensors. SNOTEL is operated by the Natural Resources Conservation Service (NRCS) of the United States Department of Agriculture in the Western United States. Plots in this module show total snow water equivalent (SWE) and total liquid precipitation (rain + SWE) and compares these to historical averages. 

---